name: base
category: dev
channels:
  - conda-forge
  - default
dependencies:
  - python
  - jupyterlab
  - pandas
  - shapely
  - contextily
  - jupyter
  - pyproj
  - geopandas
  - descartes
  - geojson
  - geopandas
  - rasterio
  - gdal
  - glob2
  - numpy
  - ipyleaflet
  - tqdm
  - matplotlib
  - earthpy
  - jupyter-book
  - jupyter-ai
  - bash_kernel
  - ipyleaflet
  - cartopy
  - rioxarray
  - sparqlwrapper
  - contextily
  - matplotlib
  - basemap
  - basemap-data
  - basemap-data-hires
  - chromadb
  - langchain
  - GitPython
  - pytest
  - faiss-cpu
  - black
  - coverage
  - pytest-cov
  - flake8
  - pytest-notebook
  - tox
  - openai
  - tiktoken
  - elasticsearch
  - termcolor
  - gymnasium
  - transformers[agents]
  - faiss-cpu
  - pytorch
  - tensorflow
  - diffusers
  - matplotlib
  - sentence-transformers
  - pandas
  - pydantic
  - lxml