[workspace]
authors = ["atrawog <atrawog@gmail.com>"]
channels = ["conda-forge"]
name = "workspace"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
python = "python"
install-dev = "pip install -e ."
test = "pip install -e . && PYTHONPATH=/workspace python -m unittest discover -s src/ecovoyage/tests"
test-all = "pip install -e . && PYTHONPATH=/workspace python -m unittest discover -s src/ecovoyage/tests && AIRFLOW_HOME=/workspace/airflow PYTHONPATH=/workspace:$PYTHONPATH TZ=UTC AIRFLOW__LOGGING__LOGGING_LEVEL=CRITICAL pixi run airflow-test-ecovoyage"
run = "python -m ecovoyage.main"
download = "python -m ecovoyage.main --download"
install = "python -m pip install -e ."
activate = "echo 'Development environment activated with editable install'"
# Airflow tasks
airflow-install-deps = "pip install flask-session==0.4.0 werkzeug==2.2.3"
airflow-migrate = "AIRFLOW_HOME=/workspace/airflow TZ=UTC airflow db migrate"
airflow-standalone = "AIRFLOW_HOME=/workspace/airflow TZ=UTC airflow standalone"
airflow-api-server = "AIRFLOW_HOME=/workspace/airflow TZ=UTC airflow api-server --port 8080"
airflow-scheduler = "AIRFLOW_HOME=/workspace/airflow TZ=UTC airflow scheduler"
airflow-dag-processor = "AIRFLOW_HOME=/workspace/airflow TZ=UTC airflow dag-processor"
airflow-triggerer = "AIRFLOW_HOME=/workspace/airflow TZ=UTC airflow triggerer"
airflow-setup = "mkdir -p /workspace/airflow && pip install flask-session==0.4.0 werkzeug==2.2.3 && AIRFLOW_HOME=/workspace/airflow TZ=UTC airflow db migrate"
airflow-test-ecovoyage = "AIRFLOW_HOME=/workspace/airflow TZ=UTC PYTHONPATH=/workspace:$PYTHONPATH airflow tasks test ecovoyage_dag check_environment 2025-05-20"
airflow-test-ecovoyage-all = "chmod +x /workspace/run_ecovoyage_tasks.sh && /workspace/run_ecovoyage_tasks.sh"

[activation]
scripts = ["python -m pip install -e ."]

[dependencies]
python = ">=3.12,<3.13"
pytest = ">=7.0.0"
setuptools = ">=68.0.0"
pip = ">=23.0.0"
requests = ">=2.31.0"
apache-airflow = ">=3.0.0,<3.1.0"
apache-airflow-providers-http = ">=4.1.0"
apache-airflow-providers-sqlite = ">=3.4.0"
tzdata = ">=2023.3"
flask-appbuilder = ">=4.3.0"
