[workspace]
authors = ["atrawog <atrawog@gmail.com>"]
channels = ["conda-forge"]
name = "workspace"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
python = "python"
test = "python -m unittest discover -s src/ecovoyage/tests"
run = "python -m ecovoyage.main"
download = "python -m ecovoyage.main --download"
install = "python -m pip install -e ."
activate = "echo 'Development environment activated with editable install'"

[activation]
scripts = ["python -m pip install -e ."]

[dependencies]
python = ">=3.13.3,<3.14"
pytest = ">=7.0.0"
setuptools = ">=68.0.0"
pip = ">=23.0.0"
requests = ">=2.31.0"
